[package]
name = "spectraplex"
version = "0.1.0"
edition = "2024"

[dependencies]
yellowstone-grpc-client = "10.2.0" # Check latest version
yellowstone-grpc-proto = "10.1.1"
solana-sdk = "3.0.0"
solana-account-decoder = "3.1.4"
tokio = "1.48.0"
futures = "0.3"
